Added docstring examples to basis functions
flatironinstitute/nemos pull request #251
Opened 2024-10-21 00:40 UTC by pranmod01

What I added: Simple examples for the public-facing functions of the Basis classes. Because most of the class definitions are derived the abstract classes, I didn't add examples to each class/function to avoid redundancy. 

Potential discussion: Similar to glm examples, I think the examples can be more in depth and/or add different contexts where the functions might be used. But I'm unsure on the domain knowledge so would need more guidance there. This is just my initial idea, and I’m open to feedback to make the examples more detailed.

2024-10-21 18:56 UTC, BalzaniEdoardo requested changes
Hi Pranati,
First of all, nice work! The examples are looking good.

We are still missing a few of user facing methods, for example,
- compute_features for Basis
- __call__ for all concrete classes
- evaluate_on_grid for all concrete classes.

Might sound like repetition, but we should think of docstrings of these classes as an helper for the user, so repetition in this case is good.
It's likely that the user will look for an example on the method of the concrete sub-class that he is currently using and the info should be there.

After this, we are ready to merge this one

2024-10-21 18:56 UTC, BalzaniEdoardo commented on src/nemos/basis.py
> +        >>> transformer_fitted = transformer.fit(X) # input must be a 2d array
I would comment about what "fit" is doing here. Say something like: fit in mode"conv" creates the set of basis that will be convolve with the input. In mode "eval" does nothing, but we need the method to fully comply with sklearn API.

2024-10-21 18:56 UTC, BalzaniEdoardo commented on src/nemos/basis.py
> +    >>> X, y = np.random.normal(size=(30, 2)), np.random.poisson(size=30)
add a comment saying 
```python
>>> # X.shape is (n_samples, n_inputs), where n_inputs is the number required by the basis
```

2024-10-21 18:56 UTC, BalzaniEdoardo commented on src/nemos/basis.py
> +    # can multiply or add another basis to the AdditiveBasis object
warn that the number of output features of the basis grows as the product of the n_features of the 1d basis. if you have 10, 15 and 100, the final basis will output 15000, as you are showing

2024-10-21 18:56 UTC, BalzaniEdoardo commented on src/nemos/basis.py
> +        >>> basis = MSplineBasis(10)
```suggestion
        >>> basis = MSplineBasis(10, mode="conv", window_size=200)
```

2024-10-21 18:56 UTC, BalzaniEdoardo commented on src/nemos/basis.py
> +        >>> transformer_fitted = transformer.fit(X) # input must be a 2d array
Assume that the
```suggestion
        >>> # Before calling `fit` the convolution kernel is not set
        >>> transformer.kernel_
        
        >>> transformer_fitted = transformer.fit(X) # input must be a 2d array
        >>> # Now the convolution kernel is initialized and has shape (window_size, n_basis_funcs)
        >>> transformer_fitted.kernel.shape
        (200, 10)
        
```

2024-10-21 18:56 UTC, BalzaniEdoardo commented on src/nemos/basis.py
> +        >>> X, y = np.random.normal(size=(100, 2)), np.random.uniform(size=100)
```suggestion
        >>> X, y = np.random.normal(size=(100, 1)), np.random.uniform(size=100)
```

2024-10-21 18:56 UTC, BalzaniEdoardo commented on src/nemos/basis.py
> +        >>> feature_transformed = transformer.fit_transform(X[:, 0:1]) # input must be a 2d array, (num_samples, 1)
```suggestion
        >>> feature_transformed = transformer.fit_transform(X) # input must be a 2d array, (num_samples, 1)
```

2024-10-21 18:58 UTC, BalzaniEdoardo commented
> What I added: Simple examples for the public-facing functions of the Basis classes. Because most of the class definitions are derived the abstract classes, I didn't add examples to each class/function to avoid redundancy.
> 
> Potential discussion: Similar to glm examples, I think the examples can be more in depth and/or add different contexts where the functions might be used. But I'm unsure on the domain knowledge so would need more guidance there. This is just my initial idea, and I’m open to feedback to make the examples more detailed.

I think this is a good point, but probably, we should keep the example simple in the docstrings and have a link to other parts of the documentation in which we showcase the use of basis more in depth!

2024-10-22 05:57 UTC, pranmod01 commented
I have started this branch from the glm branch instead of the `main` branch. So I am deleting this branch and will start a new branch with a similar name containing basis examples and no glm examples—closing this PR.

2024-10-22 05:57 UTC, closed without merging