Started basis examples
flatironinstitute/nemos pull request #253
Opened 2024-10-22 06:10 UTC by pranmod01

I deleted the old glm redundant branch and created a new one. I included the comments Edoardo made on the previous basis PR. But I need to add more examples for the subclasses and inherited methods. Hope everything is clean now!

2024-10-22 06:12 UTC, pranmod01 commented
Some tests are failing and I will fix them tomorrow.

2024-10-24 03:06 UTC, pranmod01 commented
Fixed comments from PR [PR: https://github.com/flatironinstitute/nemos/pull/251](https://github.com/flatironinstitute/nemos/pull/251)

2024-10-25 13:47 UTC, BalzaniEdoardo requested changes
A few small changes and this is also good to go. Thanks!

2024-10-25 13:47 UTC, BalzaniEdoardo commented on src/nemos/basis.py
> +        >>> X, y = np.random.normal(size=(100, 2)), np.random.uniform(size=100)
```suggestion
        >>> X = np.random.normal(size=(100, 2))
```

2024-10-25 13:47 UTC, BalzaniEdoardo commented on src/nemos/basis.py
> +        # Example input
```suggestion
        >>> # Example input
```

2024-10-25 13:47 UTC, BalzaniEdoardo commented on src/nemos/basis.py
> +        # Define and fit tranformation basis
```suggestion
        >>> # Define and fit tranformation basis
```

2024-10-25 13:47 UTC, BalzaniEdoardo commented on src/nemos/basis.py
> +        # Example input
for consistency with the other examples

2024-10-25 13:47 UTC, BalzaniEdoardo commented on src/nemos/basis.py
> +        >>> transformer_fitted = transformer.fit(X) # input must be a 2d array
```suggestion
        >>> transformer_fitted = transformer.fit(X)  # input must be a 2d array
```

2024-10-25 13:47 UTC, BalzaniEdoardo commented on src/nemos/basis.py
> +        >>> X, y = np.random.normal(size=(10000, 2)), np.random.uniform(size=100)
```suggestion
        >>> X = np.random.normal(size=(10000, 2))
```

2024-10-25 13:47 UTC, BalzaniEdoardo commented on src/nemos/basis.py
> +        >>> mspline_basis = MSplineBasis(n_basis_funcs=4, order=3)
```suggestion

        >>> mspline_basis = MSplineBasis(n_basis_funcs=4, order=3)
```

2024-10-25 13:47 UTC, BalzaniEdoardo commented on src/nemos/basis.py
> +    >>> import nemos as nmo
```suggestion
    >>> import nemos as nmo
    
```

2024-10-25 13:47 UTC, BalzaniEdoardo commented on src/nemos/basis.py
> +    >>> X, y = np.random.normal(size=(30, 2)), np.random.poisson(size=30)
```suggestion
    >>> X = np.random.normal(size=(30, 2))
```

2024-10-25 13:47 UTC, BalzaniEdoardo commented on src/nemos/basis.py
> +    >>> X, y = np.random.normal(size=(30, 3)), np.random.poisson(size=30)
```suggestion
    >>> X = np.random.normal(size=(30, 3))
```

2024-10-25 13:47 UTC, BalzaniEdoardo commented on src/nemos/basis.py
> +        >>> from nemos.basis import BSplineBasis
```suggestion
        >>> from nemos.basis import BSplineBasis
        
```

2024-10-25 13:47 UTC, BalzaniEdoardo commented on src/nemos/basis.py
> +        >>> cyclic_basis = CyclicBSplineBasis(n_basis_funcs=4, order=3)
```suggestion
        >>> cyclic_basis = CyclicBSplineBasis(n_basis_funcs=4, order=3)
        
```

2024-10-25 13:47 UTC, BalzaniEdoardo commented on src/nemos/basis.py
> +        >>> from nemos.basis import RaisedCosineBasisLinear
```suggestion
        >>> from nemos.basis import RaisedCosineBasisLinear
        
```

2024-10-25 13:47 UTC, BalzaniEdoardo commented on src/nemos/basis.py
> +    >>> n_basis_funcs = 5
```suggestion

    >>> n_basis_funcs = 5
```

2024-10-25 13:47 UTC, BalzaniEdoardo commented on src/nemos/basis.py
> +    >>> decay_rates = [0.01, 0.02, 0.03, 0.04, 0.05] # sample decay rates
```suggestion
    >>> decay_rates = [0.01, 0.02, 0.03, 0.04, 0.05]  # sample decay rates
```

2024-10-25 13:47 UTC, BalzaniEdoardo commented on src/nemos/basis.py
> +        >>> n_basis_funcs = 5
```suggestion

        >>> n_basis_funcs = 5
```

2024-10-25 19:00 UTC, billbrod commented on src/nemos/basis.py
> +    >>> # X.shape is (n_samples, n_inputs), where n_inputs is the number required by the basis
I don't think this comment is necessary

2024-10-25 19:01 UTC, billbrod commented on src/nemos/basis.py
> +    >>> multiplicative_basis = nmo.basis.MultiplicativeBasis(basis1=basis_1, basis2=basis_2)
@BalzaniEdoardo same question about whether we want to show this

2024-10-25 19:01 UTC, billbrod commented on src/nemos/basis.py
> +    >>> transformed_X = multiplicative_basis.to_transformer().transform(X[:, 0:2])
Same point about not showing to_transformer

2024-10-25 19:01 UTC, billbrod commented on src/nemos/basis.py
> +    >>> transformed_X = multiplicative_basis_2.to_transformer().transform(X)
Same point about not showing to_transformer

2024-10-25 19:01 UTC, billbrod commented on src/nemos/basis.py
> +    >>> bspline_transformer = bspline_basis.to_transformer()
Same point about not showing to_transformer

2024-10-25 19:02 UTC, billbrod commented on src/nemos/basis.py
> +    >>> X_transformed = cyclic_basis.to_transformer().fit_transform(X)
Same point about not showing to_transformer

2024-10-25 19:02 UTC, billbrod commented on src/nemos/basis.py
> +    >>> X_transformed = cosine_basis.to_transformer().fit_transform(X)
Same point about not showing to_transformer

2024-10-25 19:03 UTC, billbrod commented on src/nemos/basis.py
> +    >>> X_transformed = cosine_basis.to_transformer().fit_transform(X)
Same point about not showing to_transformer

2024-10-25 19:03 UTC, billbrod commented on src/nemos/basis.py
> +    >>> X_transformed = ortho_basis.to_transformer().fit_transform(X)
Same point about not showing to_transformer

2024-10-25 19:04 UTC, billbrod commented on src/nemos/basis.py
> +    >>> bspline_eval = bspline(sample_points, knots) # define a cubic B-spline
What's up with knot=knot=?

And shouldn't show a hidden function here

2024-10-26 20:54 UTC, pranmod01 commented on src/nemos/basis.py
> +    >>> additive_basis = nmo.basis.AdditiveBasis(basis1=basis_1, basis2=basis_2)
I show that way too couple of lines down. Thought it might be helpful to show that it can be defined both ways.

2024-10-28 17:59 UTC, BalzaniEdoardo approved these changes
Remove the init of additive basis from the example, and this is ready to merge too.
I merge development also, I have merged the GLM example PR and I am going to merge another PR as well before this one (the SVRG auto-stepsize)

2024-10-28 17:59 UTC, BalzaniEdoardo commented on src/nemos/basis.py
> +    >>> additive_basis = nmo.basis.AdditiveBasis(basis1=basis_1, basis2=basis_2)
I agree with Billy on this one, we never show that syntax in the rest of the docs

2024-10-28 18:40 UTC, billbrod approved these changes
Once you make the change Edoardo mentioned, this is good with me!

2024-10-31 13:05 UTC, merged