Improve transformer api
flatironinstitute/nemos pull request #280
Opened 2024-12-14 16:18 UTC by BalzaniEdoardo

Small PR allowing the chaining behavior of `TransformerBasis`.

Before this PRs, basis methods returning `self` could not be chained when the basis was wrapped by the `TransformerBasis` class.

Old behavior

```python
# this would raise an error since the output of `transforemer_basis.set_input_shape` is `self.basis` instead of `self`.
transformer_basis.set_input_shape(inp_shape).fit(X)
```

New behavior

```python
# this works fine
transformer_basis.set_input_shape(inp_shape).fit(X)
```

## Key Features
- Decorator that post-process the output of chainable basis methods, which grabs the method output and set the `_basis` of transformer to the output
- New tuple attribute of the TransformerBasis class listing all the chainable methods of basis.
- Run-time decoration of methods in the `__getattr__` when first called + caching. Run-time decorating is necessary because if set at initialization, it would create a circular reference, and result in infinite loop when pickling.

2024-12-17 21:18 UTC, sjvenditto approved these changes
I committed a fix to a couple typos I found, otherwise it looks good!

2024-12-17 23:15 UTC, BalzaniEdoardo commented
Great! Thanks


On Tue, Dec 17, 2024, 4:19 PM Sarah Jo Venditto ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> I committed a fix to a couple typos I found, otherwise it looks good!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/flatironinstitute/nemos/pull/280#pullrequestreview-2510153279>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AG2MOSYD5MLCEFD7JFINZR32GCINJAVCNFSM6AAAAABTTVEBUKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMJQGE2TGMRXHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-19 15:27 UTC, billbrod requested changes
Don't really have any notes about the chaining, that all looks good to me.

- `TransformerBasis` objects have a `to_transformer()` method, which I think just returns self. This is a bit confusing -- is there a reason to have this behavior?
- `transform` and `fit_transform` should have the notes about `set_input_shape` being called first as well (like `fit`), as well as the Raises section of the docstring

2024-12-19 21:09 UTC, BalzaniEdoardo commented on src/nemos/basis/_transformer_basis.py
> +        Checks the input structure and, if any of the 1D basis in self._basis is in "conv" mode,
Yes, I'll remove the properties

2024-12-19 22:48 UTC, BalzaniEdoardo commented on src/nemos/basis/_transformer_basis.py
> +        if name in ["_basis", "basis", "_wrapped_methods"]:
I did remove the property and store directly basis in `self.basis`. We need it writable to cross validate the basis directly

2024-12-19 22:49 UTC, BalzaniEdoardo commented on tests/test_transformer_basis.py
> +    list_all_basis_classes(),
yes, exactly, the composite bases are included otherwise

2024-12-20 03:53 UTC, merged