Pytree refactor
flatironinstitute/nemos pull request #77
Opened 2023-12-20 22:43 UTC by billbrod

Just opening this right now so that we can get the GLM example rendered by read the docs. More work needs to be done here.

For the example in particular:
- I'm using a dataset from DANDI, looking at head direction and 2d position.
- I think this example is too complex to introduce the pytrees and more/better text is needed here.
- Writing this made it clear that we can easily put together some simple helper functions that will make things easier, like doing the multiplication between bases and coefficients.
- When this goes into the docs, the general "here's a pytree" should probably be a separate tutorial from "here's how to use them with GLMs".

2024-01-03 21:47 UTC, gviejo commented on docs/examples/plot_glm_pytree.py
> +X = nmo.pytrees.FeaturePytree(head_direction=np.expand_dims(basis.evaluate(head_dir.values), 1))
Also why the expand_dims?

2024-01-05 19:04 UTC, billbrod commented on docs/examples/plot_glm_pytree.py
> +X = nmo.pytrees.FeaturePytree(head_direction=np.expand_dims(basis.evaluate(head_dir.values), 1))
as discussed, expand_dims adds an extra dimension for (the single) neurons. We should think about how to handle this, but it's not a pytree problem

2024-01-05 20:04 UTC, billbrod commented
I addressed Guillaume's comments and added tests for pytrees. There weren't many, but I think they're sufficient. Let me know if there's anything else I should add to them.

2024-01-05 21:10 UTC, billbrod commented
Currently, one test is failing:
- `test_fit_init_params_type`: when input is `iter` or a dict with keys `p1,p2`. The problem is that we expect `params` to be a 2-tuple (in order  to be compliant with sklearn, I thin), but this leads to some weirdness, as in these cases. We should talk through this

2024-01-08 14:11 UTC, BalzaniEdoardo commented on docs/examples/plot_glm_pytree.py
> +mapped = jax.tree_map(lambda x: jnp.mean(x, axis=-1), example_pytree)
Agree

2024-01-08 15:41 UTC, BalzaniEdoardo requested changes
great work; I added a couple of commits. 
**First commit content:**
1. Add 1-line docstrings to tests.
2. Assert that tree_map returns a FeaturePytree
3. moved the --cov from the general config to the tox.ini call to pytest; the debugger behaves poorly if tests are configured with cov (doesn't stop at breakpoints)

**Second commit content:**
1. Added a test for asserting the equivalence of fitting a glm using pytrees or arrays

2024-01-08 21:00 UTC, BalzaniEdoardo approved these changes
good to go!

2024-01-08 21:19 UTC, merged