changed correlatio to pytree
flatironinstitute/nemos pull request #82
Opened 2024-01-13 14:49 UTC by BalzaniEdoardo

This small PR replaces the loop over trials in the convolution_1d with a tree map.

2024-01-16 15:29 UTC, billbrod requested changes
I think there's a typo in the change, see my comment for details.

Also, should add tests.

2024-01-16 15:29 UTC, billbrod commented on src/nemos/utils.py
> +            time_series, basis_matrix
I think this is a typo right? Putting `basis_matrix` as an arg to tree_map means that it should be a pytree with the same structure as `time_series`, but including in the call the `_CORR_VARIABLE_TRIAL_DUR` means that it's being correlated with each leaf. shouldn't it be something like:
```suggestion
            lambda x, y: _CORR_VARIABLE_TRIAL_DUR(jnp.atleast_2d(x), y),
            time_series, basis_matrix
```

2024-01-16 15:29 UTC, billbrod commented on src/nemos/utils.py
> +) -> Union[Iterable[NDArray], NDArray, Iterable[jnp.ndarray], jnp.ndarray]:
I'm confused by the `Iterable` in the type hinting here (both for return and `time_series`). Why do that instead of List?

2024-01-16 15:29 UTC, billbrod commented on src/nemos/utils.py
> +            time_series, basis_matrix
Or it should be:
```suggestion
            lambda x: _CORR_VARIABLE_TRIAL_DUR(jnp.atleast_2d(x), basis_matrix),
            time_series
```

2024-01-31 20:15 UTC, BalzaniEdoardo reviewed
PR is ready on my side

2024-02-07 20:56 UTC, billbrod commented on src/nemos/utils.py
> +) -> Union[Iterable[NDArray], NDArray, Iterable[jnp.ndarray], jnp.ndarray]:
Is this the current best practice for pytree annotation? That feels ... not great. Maybe we can be more specific about this? As in, we look for how we use it in our docs and library, and set it to that. Or make it clear somewhere else?

2024-02-07 20:56 UTC, billbrod commented on src/nemos/utils.py
> +) -> Union[Iterable[NDArray], NDArray, Iterable[jnp.ndarray], jnp.ndarray]:
I guess the docstring can be more specific

2024-02-09 17:21 UTC, billbrod requested changes
Generally looks good, just a couple consistency fixes.

- `utils.py` line 319, above the definition of `adjust_indices`, says "add a note about this in docstrings". I agree, there should be a note!

2024-02-09 17:21 UTC, billbrod commented on src/nemos/utils.py
> +            raise AttributeError
This should be `ValueError` to match docstring ,right? And have the same error message as below.

2024-02-09 17:21 UTC, billbrod commented on src/nemos/utils.py
> +    time_series: Any, window_size: int, sample_axis: int
```suggestion
    time_series: Any, window_size: int, sample_axis: int = 0
```

2024-02-09 17:21 UTC, billbrod commented on src/nemos/utils.py
> +    check_non_empty(basis_matrix, "basis_matrix")
in practice, when could this happen? if someone messes up indexing?

2024-02-09 17:21 UTC, billbrod commented on src/nemos/utils.py
> +            raise AttributeError(
```suggestion
            raise ValueError(
```
Shouldn't this be a ValueError, to be consistent with the docstring, and the error with identical error message raised below?

2024-02-15 01:04 UTC, BalzaniEdoardo commented
> Generally looks good, just a couple consistency fixes.
> 
>     * `utils.py` line 319, above the definition of `adjust_indices`, says "add a note about this in docstrings". I agree, there should be a note!

I added a note, admittedly not the clearest, but the idea of slicing the last index in causal filter, and first in anti-causal, is the same as the reason why we were getting rid of the the last sample in the head direction tutorial:
When using the convolution output as predictor, the very last entry of the convolution output, will be used to predict the next sample, however the for the next time step we don't have matching prediction (we run out of data, quoting nemos workshop head direction tutorial, the red rectangle is out of range).

It was hard for me to explain and it is a thing we need to do and want to hide from users, because it is annoying. can you try to rephrase and explain the concept better?

2024-02-15 01:05 UTC, BalzaniEdoardo reviewed
ready for a second pass

2024-02-16 23:05 UTC, billbrod approved these changes

2024-02-16 23:12 UTC, merged